#!/usr/bin/env bash
# Configures a new Ubuntu machine to install nginx and set X-Served-By header

# Update & install nginx
sudo apt-get update -y
sudo apt-get install -y nginx

# Start nginx service
sudo systemctl enable nginx
sudo systemctl start nginx

# Allow HTTP through firewall
sudo ufw allow 'Nginx HTTP'

# Create a simple index page
echo "Hello World!" | sudo tee /var/www/html/index.html

# Set X-Served-By header with hostname
sudo sed -i '/server {/a \
    add_header X-Served-By '"$(hostname)"';' /etc/nginx/sites-available/default

# Restart nginx
sudo systemctl restart nginx

