#!/usr/bin/env bash
# Installs and configures HAProxy with roundrobin load balancing for 2 web servers

# Update and install HAProxy
sudo apt-get update -y
sudo apt-get install -y haproxy

# Enable HAProxy at system startup
sudo sed -i 's/ENABLED=0/ENABLED=1/' /etc/default/haproxy

# Backup default config
sudo cp /etc/haproxy/haproxy.cfg /etc/haproxy/haproxy.cfg.bak

# Overwrite haproxy config with load balancing
sudo tee /etc/haproxy/haproxy.cfg > /dev/null <<EOF
global
    log /dev/log    local0
    log /dev/log    local1 notice
    daemon

defaults
    log     global
    mode    http
    option  httplog
    option  dontlognull
    timeout connect 5000
    timeout client  50000
    timeout server  50000

frontend http_front
    bind *:80
    default_backend http_back

backend http_back
    balance roundrobin
    server web01 52.207.254.138:80 check
    server web02 13.218.21.126:80 check
EOF

# Restart HAProxy
sudo systemctl restart haproxy

