#!/usr/bin/env bash
# Installs and configures HAProxy with roundrobin load balancing for 2 web servers

apt-get update -y
apt-get install -y haproxy

# Enable HAProxy at system startup
sed -i 's/ENABLED=0/ENABLED=1/' /etc/default/haproxy

# Backup default config
cp /etc/haproxy/haproxy.cfg /etc/haproxy/haproxy.cfg.bak

# Overwrite haproxy config
cat <<EOF > /etc/haproxy/haproxy.cfg
global
    log /dev/log    local0
    log /dev/log    local1 notice
    daemon

defaults
    log     global
    mode    http
    option  httplog
    option  dontlognull
    timeout connect 5000
    timeout client  50000
    timeout server  50000

frontend http_front
    bind *:80
    default_backend http_back

backend http_back
    balance roundrobin
    server web01 3.93.38.36:80 check
    server web02 34.229.92.111:80 check
EOF

# Restart HAProxy
service haproxy restart
