#!/usr/bin/env bash
# Configure Nginx to have a custom 404 page

# Update packages and install nginx
sudo apt-get update
sudo apt-get install -y nginx

# Create the custom 404 page
echo "Ceci n'est pas une page" | sudo tee /etc/nginx/html/404.html

# Configure default server to use custom 404 page
sudo bash -c 'cat > /etc/nginx/sites-available/default <<EOF
server {
    listen 80 default_server;
    listen [::]:80 default_server;

    root /etc/nginx/html;
    index index.html;

    error_page 404 /404.html;

    location / {
        try_files \$uri \$uri/ =404;
    }

    location /redirect_me {
        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
    }
}
EOF'

# Restart nginx without systemctl
sudo service nginx restart

